site_name: Auburn Robotics Wiki
site_description:
  A knowledgebase for Auburn High robotics, including information on design,
  building, coding, and notebooking.
site_url: https://auburn-robotics-wiki.pages.dev
# repo_url: https://github.com/byhaydenkwon/auburn-robotics-wiki
edit_uri: https://github.com/byhaydenkwon/auburn-robotics-wiki/edit/main/docs/

nav:
  - Welcome: index.md
  - About: toplevel/about/about.md
  - Roadmap: toplevel/roadmap/roadmap.md
  - Contributing: toplevel/contributing/contributing.md
  - VEX V5 Crash Course: toplevel/vex-v5-crash-course/vex-v5-crash-course.md
  - Design:
      - Drivetrain Design: design/drivetrain-design/drivetrain-design.md
  - Hardware and Building:
      - Intro to VEX Building: building/intro-to-vex-building/intro-to-vex-building.md
      - Building Techniques: building/techniques/techniques.md
      - Advanced Building Techniques: building/advanced-techniques/advanced-techniques.md
      - Building a Drivetrain: building/building-a-drivetrain/building-a-drivetrain.md
      - Pneumatics: building/pneumatics/pneumatics.md
  - Software and Programming:
      - Programming Languages: programming/programming-languages/programming-languages.md
  - Driving and Strategy:
      - Intro to VEX Driving: driving/intro-to-vex-driving/intro-to-vex-driving.md
  - Documentation and Notebooking:
      - Placeholder: toplevel/placeholder-coming-soon/placeholder-coming-soon.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.action.edit
  icon:
    edit: material/pencil
    view: material/eye
  font:
    text: IBM Plex Sans
    code: false
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - auto-description
  - social:
      enabled: !ENV [ARW_PROD, false]
  - git-committers:
      repository: byhaydenkwon/auburn-robotics-wiki
      branch: main
      enabled: !ENV [ARW_PROD, false]
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - tables
  - meta
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
validation:
  links:
    absolute_links: ignore
extra:
  social:
    - icon: fontawesome/brands/github
      name: Auburn Robotics Wiki repo
      link: https://github.com/byhaydenkwon/auburn-robotics-wiki
copyright:
  This wiki is licensed under a <a id="copyright-notice"
  href=https://creativecommons.org/licenses/by-sa/4.0/>Creative Commons
  Attribution-ShareAlike 4.0 International</a> license.
