# Copyright (c) 2026 Hayden Kwon
# MIT License

"""
Generated by Claude Sonnet 4.6

MkDocs hook: derive page.meta['description'] from the first paragraph
after the page's Markdown title.

The first paragraph is found by scanning past the title (an ATX `# Heading`)
and skipping any further headings, code blocks, math blocks, tables,
admonitions, and blockquotes that appear before the first real paragraph.
Bold, italic, and link markup are stripped from the resulting text.
"""

import re

OVERRIDE = False  # overwrite an existing front-matter description?
MAX_LENGTH = 0  # truncate to N characters with an ellipsis; 0 = no limit

HEADING_RE = re.compile(r"^#\s+\S")
ANY_HEADING_RE = re.compile(r"^#{1,6}\s+\S")
ADMONITION_RE = re.compile(r"^(!!!|\?\?\?\+?)\s")
BLOCKQUOTE_RE = re.compile(r"^\s*>")
MATH_DOLLAR_RE = re.compile(r"^\s*\$\$")
MATH_BRACKET_RE = re.compile(r"^\s*\\\[")
TABLE_SEP_RE = re.compile(r"^\s*\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)*\|?\s*$")


def on_page_markdown(markdown, page, config, **kwargs):
    if page.meta.get("description") and not OVERRIDE:
        return markdown

    description = _extract_description(markdown)
    if description:
        page.meta["description"] = description

    return markdown


# -- extraction -----------------------------------------------------------


def _extract_description(markdown):
    lines = markdown.splitlines()
    n = len(lines)

    heading_index = None
    for idx, line in enumerate(lines):
        if HEADING_RE.match(line):
            heading_index = idx
            break

    i = heading_index + 1 if heading_index is not None else 0

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        if ANY_HEADING_RE.match(line):
            i += 1
            continue

        if stripped.startswith("```") or stripped.startswith("~~~"):
            i = _skip_fenced_code(lines, i, n)
            continue

        if MATH_DOLLAR_RE.match(line):
            i = _skip_math_dollar(lines, i, n)
            continue

        if MATH_BRACKET_RE.match(line):
            i = _skip_math_bracket(lines, i, n)
            continue

        if ADMONITION_RE.match(stripped):
            i = _skip_indented_block(lines, i, n)
            continue

        if BLOCKQUOTE_RE.match(line):
            while i < n and BLOCKQUOTE_RE.match(lines[i]):
                i += 1
            continue

        if "|" in line and i + 1 < n and TABLE_SEP_RE.match(lines[i + 1]):
            i = _skip_table(lines, i, n)
            continue

        # First real paragraph starts here.
        break

    if i >= n:
        return None

    paragraph_lines = []
    while i < n and lines[i].strip():
        paragraph_lines.append(lines[i].strip())
        i += 1

    paragraph = " ".join(paragraph_lines)
    return _clean(paragraph)


def _skip_fenced_code(lines, i, n):
    stripped = lines[i].strip()
    fence_char = stripped[0]
    fence_len = len(stripped) - len(stripped.lstrip(fence_char))
    i += 1
    while i < n and not lines[i].strip().startswith(fence_char * fence_len):
        i += 1
    return i + 1


def _skip_math_dollar(lines, i, n):
    stripped = lines[i].strip()
    if stripped.count("$$") >= 2 and len(stripped) > 2:
        return i + 1
    i += 1
    while i < n and "$$" not in lines[i]:
        i += 1
    return i + 1


def _skip_math_bracket(lines, i, n):
    i += 1
    while i < n and "\\]" not in lines[i]:
        i += 1
    return i + 1


def _skip_indented_block(lines, i, n):
    i += 1
    while i < n and (not lines[i].strip() or lines[i].startswith((" ", "\t"))):
        i += 1
    return i


def _skip_table(lines, i, n):
    i += 2  # header row + separator row
    while i < n and lines[i].strip():
        i += 1
    return i


# -- cleanup ----------------------------------------------------------------


def _clean(text):
    # Images: drop entirely (alt text usually isn't real prose).
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", text)
    # Links: keep the link text.
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    # Bold.
    text = re.sub(r"\*\*([^*]+?)\*\*", r"\1", text)
    text = re.sub(r"__([^_]+?)__", r"\1", text)
    # Italics.
    text = re.sub(r"\*([^*]+?)\*", r"\1", text)
    text = re.sub(r"(?<!\w)_([^_]+?)_(?!\w)", r"\1", text)
    # Collapse whitespace left behind by the removals above.
    text = re.sub(r"\s+", " ", text).strip()

    if MAX_LENGTH and len(text) > MAX_LENGTH:
        truncated = text[:MAX_LENGTH].rsplit(" ", 1)[0].rstrip(",.;: ")
        text = truncated + "…"

    return text
