"""
MKDocs plugin to set the description of a page from the first paragraph after the title,
skipping non-prose and stripping bold, italics, and links.

This plugin was generated by Claude Sonnet 4.6.
"""

import re

from mkdocs.config import config_options
from mkdocs.plugins import BasePlugin


class AutoDescriptionPlugin(BasePlugin):
    config_scheme = (
        # leave page alone if description already set unless true
        ("override", config_options.Type(bool, default=False)),
        # truncate the generated description (0 disables)
        ("max_length", config_options.Type(int, default=0)),
    )

    HEADING_RE = re.compile(r"^#\s+\S")
    ANY_HEADING_RE = re.compile(r"^#{1,6}\s+\S")
    ADMONITION_RE = re.compile(r"^(!!!|\?\?\?\+?)\s")
    BLOCKQUOTE_RE = re.compile(r"^\s*>")
    MATH_DOLLAR_RE = re.compile(r"^\s*\$\$")
    MATH_BRACKET_RE = re.compile(r"^\s*\\\[")
    TABLE_SEP_RE = re.compile(r"^\s*\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)*\|?\s*$")

    def on_page_markdown(self, markdown, page, config, files):
        if page.meta.get("description") and not self.config["override"]:
            return markdown

        description = self._extract_description(markdown)
        if description:
            page.meta["description"] = description

        return markdown

    def _extract_description(self, markdown):
        lines = markdown.splitlines()
        n = len(lines)

        heading_index = None
        for idx, line in enumerate(lines):
            if self.HEADING_RE.match(line):
                heading_index = idx
                break

        i = heading_index + 1 if heading_index is not None else 0

        while i < n:
            line = lines[i]
            stripped = line.strip()

            if not stripped:
                i += 1
                continue

            if self.ANY_HEADING_RE.match(line):
                i += 1
                continue

            if stripped.startswith("```") or stripped.startswith("~~~"):
                i = self._skip_fenced_code(lines, i, n)
                continue

            if self.MATH_DOLLAR_RE.match(line):
                i = self._skip_math_dollar(lines, i, n)
                continue

            if self.MATH_BRACKET_RE.match(line):
                i = self._skip_math_bracket(lines, i, n)
                continue

            if self.ADMONITION_RE.match(stripped):
                i = self._skip_indented_block(lines, i, n)
                continue

            if self.BLOCKQUOTE_RE.match(line):
                while i < n and self.BLOCKQUOTE_RE.match(lines[i]):
                    i += 1
                continue

            if "|" in line and i + 1 < n and self.TABLE_SEP_RE.match(lines[i + 1]):
                i = self._skip_table(lines, i, n)
                continue

            break

        if i >= n:
            return None

        paragraph_lines = []
        while i < n and lines[i].strip():
            paragraph_lines.append(lines[i].strip())
            i += 1

        paragraph = " ".join(paragraph_lines)
        return self._clean(paragraph)

    @staticmethod
    def _skip_fenced_code(lines, i, n):
        stripped = lines[i].strip()
        fence_char = stripped[0]
        fence_len = len(stripped) - len(stripped.lstrip(fence_char))
        i += 1
        while i < n and not lines[i].strip().startswith(fence_char * fence_len):
            i += 1
        return i + 1

    @staticmethod
    def _skip_math_dollar(lines, i, n):
        stripped = lines[i].strip()
        if stripped.count("$$") >= 2 and len(stripped) > 2:
            return i + 1
        i += 1
        while i < n and "$$" not in lines[i]:
            i += 1
        return i + 1

    @staticmethod
    def _skip_math_bracket(lines, i, n):
        i += 1
        while i < n and "\\]" not in lines[i]:
            i += 1
        return i + 1

    @staticmethod
    def _skip_indented_block(lines, i, n):
        i += 1
        while i < n and (not lines[i].strip() or lines[i].startswith((" ", "\t"))):
            i += 1
        return i

    @staticmethod
    def _skip_table(lines, i, n):
        i += 2  # header row + separator row
        while i < n and lines[i].strip():
            i += 1
        return i

    def _clean(self, text):
        # images
        text = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", text)
        # links
        text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
        # bold
        text = re.sub(r"\*\*([^*]+?)\*\*", r"\1", text)
        text = re.sub(r"__([^_]+?)__", r"\1", text)
        # italics
        text = re.sub(r"\*([^*]+?)\*", r"\1", text)
        text = re.sub(r"(?<!\w)_([^_]+?)_(?!\w)", r"\1", text)
        # whitespace
        text = re.sub(r"\s+", " ", text).strip()

        max_length = self.config.get("max_length", 0)
        if max_length and len(text) > max_length:
            truncated = text[:max_length].rsplit(" ", 1)[0].rstrip(",.;: ")
            text = truncated + "…"

        return text
